apiVersion: batch/v1
kind: Job
metadata:
  name: load-model-job-whisper-base
spec:
  template:
    spec:
      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: whisper-model-base
      containers:
      - name: model-loader
        image: python:3.11-slim
        volumeMounts:
        - mountPath: /model
          name: model
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y git ffmpeg awscli curl jo jq bc
          pip install git+https://github.com/openai/whisper.git
          python3 - << EOF
          import whisper
          whisper.load_model("base", download_root="/model")
          EOF
      restartPolicy: Never