apiVersion: batch/v1
kind: Job
metadata:
  name: test-model-job-whisper-base
spec:
  template:
    spec:
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: whisper-model-base
          readOnly: true
      containers:
      - name: model-tester
        image: python:3.11-slim
        volumeMounts:
        - mountPath: /model
          name: model
          readOnly: true
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y git ffmpeg awscli curl jo jq bc
          pip install git+https://github.com/openai/whisper.git
          python3 - << EOF
          import whisper
          import time
          print("Loading model...")
          start_time = time.time()
          whisper.load_model("base", download_root="/model")
          end_time = time.time()
          load_time = end_time - start_time
          print(f"Model loading time with pre-load: {load_time:.2f} seconds")
          EOF
      restartPolicy: Never